/**
 * Extracts the RogueEngine public API from a project's shipped `_Rogue/**.d.ts`
 * files into `data/engine-api.json`.
 *
 * The .d.ts files ARE the contract the engine ships — more accurate than the
 * published docs, and regenerated by the editor on every engine update. So the
 * MCP's data is derived from them rather than hand-transcribed.
 *
 *   npm run extract -- --project <path-to-RogueEngine-project>
 *   npm run extract -- --project <path> --check    (report drift, write nothing)
 *
 * Design notes (each of these is load-bearing):
 *  - We resolve ONE module (the `rogue-engine.d.ts` barrel) and enumerate its
 *    exports via the TypeChecker, rather than walking files. `props`,
 *    `AssetManager` and `Runtime` are instances of NON-exported classes, so an
 *    AST file-walk cannot see them.
 *  - Members come from `checker.getPropertiesOfType()`, which includes
 *    INHERITED members, then get filtered to declarations under `_Rogue/`.
 *    `Runtime.timer` is declared on SceneController — a per-file walk would
 *    miss it and regenerate the very `Runtime.clock` bug this replaces.
 *  - Built-in components are identified by the `static isInternalComponent`
 *    marker, not a name list, so new ones appear automatically.
 */
import * as ts from 'typescript';
import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const HERE = path.dirname(fileURLToPath(import.meta.url));
const REPO_ROOT = path.resolve(HERE, '..', '..');

const SCHEMA_VERSION = 1;
const MAX_TYPE_LEN = 120;
const MAX_OVERLOADS = 6;

// ---------------------------------------------------------------------------
// Shapes (mirrored by src/engine-api-types.ts)
// ---------------------------------------------------------------------------
interface PropertyInfo {
  name: string; type: string; description: string;
  readonly?: boolean; static?: boolean; inheritedFrom?: string; deprecated?: string;
}
interface MethodInfo {
  name: string; signature: string; description: string;
  signatures?: string[]; example?: string; static?: boolean;
  inheritedFrom?: string; deprecated?: string;
}
interface ClassInfo {
  name: string; description: string; kind: 'class' | 'component' | 'singleton' | 'functions';
  group?: string; baseClass?: string;
  properties: PropertyInfo[]; methods: MethodInfo[];
  staticProperties?: PropertyInfo[]; staticMethods?: MethodInfo[];
}

// ---------------------------------------------------------------------------
// Args
// ---------------------------------------------------------------------------
const argv = process.argv.slice(2);
const getArg = (n: string): string | undefined => {
  const i = argv.indexOf(n);
  return i >= 0 ? argv[i + 1] : undefined;
};
const projectArg = getArg('--project');
const checkOnly = argv.includes('--check');

if (!projectArg) {
  console.error('ERROR: --project <path-to-RogueEngine-project> is required.\n' +
    'The .d.ts files live in a RogueEngine project, not in this repo.');
  process.exit(1);
}
const project = path.resolve(projectArg);
const barrel = path.join(project, '_Rogue', 'rogue-engine.d.ts');
const rogueTsconfig = path.join(project, 'tsconfig.rogue.json');

if (!fs.existsSync(barrel)) {
  console.error(`ERROR: could not find the engine barrel file.\n  looked for: ${barrel}\n` +
    `Is "${project}" a RogueEngine project? Open it in the editor once to generate _Rogue/.`);
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Program
// ---------------------------------------------------------------------------
let options: ts.CompilerOptions = { skipLibCheck: true, noEmit: true, target: ts.ScriptTarget.ES2022 };
if (fs.existsSync(rogueTsconfig)) {
  const cf = ts.readConfigFile(rogueTsconfig, ts.sys.readFile);
  if (!cf.error) {
    const parsed = ts.parseJsonConfigFileContent(cf.config, ts.sys, project);
    options = { ...parsed.options, skipLibCheck: true, noEmit: true };
  }
} else {
  console.warn(`WARN: ${rogueTsconfig} not found — "three" may resolve to any, degrading types.`);
}

const program = ts.createProgram({ rootNames: [barrel], options });
const checker = program.getTypeChecker();
const sourceFile = program.getSourceFile(barrel);
if (!sourceFile) {
  console.error(`ERROR: TypeScript could not load ${barrel}`);
  process.exit(1);
}
const moduleSymbol = checker.getSymbolAtLocation(sourceFile);
if (!moduleSymbol) {
  console.error('ERROR: barrel has no module symbol (is it empty?)');
  process.exit(1);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
const norm = (p: string) => p.replace(/\\/g, '/');
const ROGUE_DIR = norm(path.join(project, '_Rogue')) + '/';

const TYPE_FLAGS =
  ts.TypeFormatFlags.NoTruncation |
  ts.TypeFormatFlags.UseAliasDefinedOutsideCurrentScope;

/** `import("three").Object3D<...>` is noise that bloats every tool response. */
function cleanType(s: string): string {
  s = s.replace(/import\("[^"]*"\)\./g, '').replace(/\s+/g, ' ').trim();
  if (s.length > MAX_TYPE_LEN) {
    const stripped = s.replace(/<[^<>]*>/g, '');
    s = stripped.length <= MAX_TYPE_LEN ? stripped : s.slice(0, MAX_TYPE_LEN - 1) + '…';
  }
  return s;
}
const printType = (t: ts.Type, at?: ts.Node) => cleanType(checker.typeToString(t, at, TYPE_FLAGS));

/** JSDoc {@link Foo} survives displayPartsToString as literal braces; unwrap it. */
function unlink(t: string): string {
  return t.replace(/\{@link\s+([^}|]+)(?:\|[^}]*)?\}/g, '$1').trim();
}

function docOf(sym: ts.Symbol): string {
  return unlink(ts.displayPartsToString(sym.getDocumentationComment(checker)).replace(/\s+/g, ' ').trim());
}
function tagOf(sym: ts.Symbol, tag: string): string | undefined {
  const t = sym.getJsDocTags(checker).find(x => x.name === tag);
  if (!t) return undefined;
  const text = ts.displayPartsToString(t.text ?? []).trim();
  return text || (tag === 'deprecated' ? 'deprecated' : undefined);
}
function exampleOf(sym: ts.Symbol): string | undefined {
  const ex = tagOf(sym, 'example');
  if (!ex) return undefined;
  return ex.replace(/^```[a-z]*\n?/i, '').replace(/```$/, '').trim() || undefined;
}

const isUnderRogue = (d: ts.Declaration) => norm(d.getSourceFile().fileName).startsWith(ROGUE_DIR);
const declOf = (s: ts.Symbol): ts.Declaration | undefined => s.valueDeclaration ?? s.declarations?.[0];
const fileTag = (d: ts.Declaration) =>
  path.basename(d.getSourceFile().fileName).replace(/\.d\.ts$/, '').replace(/\.re$/, '');

const SKIP_NAMES = new Set([
  'prototype', 'isInternalComponent', 'apply', 'call', 'bind',
  'toString', 'caller', 'length', 'arguments', 'constructor',
]);

function skipMember(sym: ts.Symbol): boolean {
  const name = sym.getName();
  if (name.startsWith('_') || SKIP_NAMES.has(name)) return true;
  if (sym.flags & ts.SymbolFlags.Prototype) return true;
  const decls = sym.declarations ?? [];
  if (!decls.length) return true;
  if (!decls.some(isUnderRogue)) return true; // drops the entire THREE.Object3D surface
  const mods = ts.getCombinedModifierFlags(decls[0]);
  if (mods & (ts.ModifierFlags.Private | ts.ModifierFlags.Protected)) return true;
  return false;
}

/** JSDoc on an accessor pair lives on the getter; prefer whichever has text. */
function bestDoc(sym: ts.Symbol): string {
  const d = docOf(sym);
  if (d) return d;
  for (const decl of sym.declarations ?? []) {
    const nameNode = (decl as { name?: ts.Node }).name;
    if (!nameNode) continue;
    const s = checker.getSymbolAtLocation(nameNode);
    if (s) {
      const dd = docOf(s);
      if (dd) return dd;
    }
  }
  return '';
}

/**
 * Types reached through a property that are themselves classes declared under
 * _Rogue/ — e.g. RE.Input.keyboard is a `Keyboard`. Those classes are not
 * barrel-exported but carry the API people actually call, so collect them for a
 * second pass. Discovered by following types, never by a hardcoded name list.
 */
const nestedCandidates = new Map<string, ts.Type>();
function recordNested(t: ts.Type) {
  const target = (t.getSymbol()?.flags ?? 0) & ts.SymbolFlags.Alias
    ? checker.getAliasedSymbol(t.getSymbol()!) : t.getSymbol();
  if (!target) return;
  const name = target.getName();
  if (!/^[A-Z][\w]*$/.test(name)) return;
  const d = declOf(target);
  if (!d || !isUnderRogue(d) || !ts.isClassDeclaration(d)) return;
  if (!nestedCandidates.has(name)) nestedCandidates.set(name, t);
}

function extractMembers(type: ts.Type, isStatic: boolean, ownFile?: string) {
  const properties: PropertyInfo[] = [];
  const methods: MethodInfo[] = [];

  for (const sym of checker.getPropertiesOfType(type)) {
    if (skipMember(sym)) continue;
    const decls = sym.declarations!;
    const decl = declOf(sym)!;
    const name = sym.getName();
    const description = bestDoc(sym);
    const deprecated = tagOf(sym, 'deprecated');
    const src = fileTag(decl);
    const inheritedFrom = ownFile && src !== ownFile ? src : undefined;

    const isMethodDecl = decls.some(d =>
      ts.isMethodDeclaration(d) || ts.isMethodSignature(d) || ts.isFunctionDeclaration(d));
    const t = checker.getTypeOfSymbolAtLocation(sym, decl);
    const sigs = t.getCallSignatures();

    if (isMethodDecl && sigs.length) {
      const all = sigs.map(s => `${name}${cleanType(checker.signatureToString(s, decl, TYPE_FLAGS))}`);
      const m: MethodInfo = { name, signature: all[0], description };
      if (all.length > 1) {
        m.signatures = all.slice(0, MAX_OVERLOADS);
        if (all.length > MAX_OVERLOADS) {
          m.signatures.push(`…and ${all.length - MAX_OVERLOADS} more overloads`);
        }
      }
      const ex = exampleOf(sym);
      if (ex) m.example = ex;
      if (isStatic) m.static = true;
      if (inheritedFrom) m.inheritedFrom = inheritedFrom;
      if (deprecated) m.deprecated = deprecated;
      methods.push(m);
    } else {
      const hasGet = decls.some(ts.isGetAccessorDeclaration);
      const hasSet = decls.some(ts.isSetAccessorDeclaration);
      const readonly = (hasGet && !hasSet) ||
        !!(ts.getCombinedModifierFlags(decl) & ts.ModifierFlags.Readonly);
      recordNested(t);
      const p: PropertyInfo = { name, type: printType(t, decl), description };
      if (readonly) p.readonly = true;
      if (isStatic) p.static = true;
      if (inheritedFrom) p.inheritedFrom = inheritedFrom;
      if (deprecated) p.deprecated = deprecated;
      properties.push(p);
    }
  }
  const byName = (a: { name: string }, b: { name: string }) => a.name.localeCompare(b.name);
  return { properties: properties.sort(byName), methods: methods.sort(byName) };
}

/**
 * `export default class Character extends RE.Component` surfaces its base as the
 * symbol literally named "default". Recover the real class name from the
 * declaration, falling back to the declaring file name.
 */
function resolveBaseName(baseSym: ts.Symbol | undefined): string | undefined {
  if (!baseSym) return undefined;
  const n = baseSym.getName();
  if (n && n !== 'default' && n !== '__type') return n;
  const d = declOf(baseSym);
  if (!d) return undefined;
  const named = (d as { name?: ts.Identifier }).name;
  if (named && ts.isIdentifier(named)) return named.text;
  return fileTag(d);
}

function groupOf(decl: ts.Declaration): string {
  const f = norm(decl.getSourceFile().fileName);
  const m = f.match(/\/Components\/([^/]+)\//);
  if (!m) return 'Core';
  return m[1] === 'ContactFX' ? 'FX' : m[1]; // UI | Audio | Weapon | Camera | CSS2D | HTMLMesh
}

// ---------------------------------------------------------------------------
// Walk the barrel's exports
// ---------------------------------------------------------------------------
const classes: Record<string, ClassInfo> = {};
const components: Record<string, ClassInfo> = {};
const functionGroups: Record<string, ClassInfo> = {};
const types: { name: string; description: string }[] = [];

const moduleExports = checker.getExportsOfModule(moduleSymbol);

for (const rawSym of moduleExports) {
  const sym = rawSym.flags & ts.SymbolFlags.Alias ? checker.getAliasedSymbol(rawSym) : rawSym;
  const name = rawSym.getName();
  const decl = declOf(sym);
  if (!decl || !isUnderRogue(decl)) continue;

  // Free functions -> grouped into a pseudo-class named after their file.
  // Detect by TYPE, not declaration kind: much of ComponentsManager is exported
  // as `export declare const getComponents: <T>(...) => T[]`, which is not a
  // FunctionDeclaration but is absolutely a function to the caller.
  const symType = checker.getTypeOfSymbolAtLocation(sym, decl);
  const isCallable = symType.getCallSignatures().length > 0 &&
    symType.getConstructSignatures().length === 0;
  if (ts.isFunctionDeclaration(decl) || isCallable) {
    const g = fileTag(decl);
    functionGroups[g] ??= {
      name: g, description: `${g} exported directly on RE.`,
      kind: 'functions', properties: [], methods: [],
    };
    const t = checker.getTypeOfSymbolAtLocation(sym, decl);
    const all = t.getCallSignatures()
      .map(s => `${name}${cleanType(checker.signatureToString(s, decl, TYPE_FLAGS))}`);
    const m: MethodInfo = { name, signature: all[0] ?? `${name}()`, description: bestDoc(sym) };
    if (all.length > 1) m.signatures = all.slice(0, MAX_OVERLOADS);
    const ex = exampleOf(sym);
    if (ex) m.example = ex;
    const dep = tagOf(sym, 'deprecated');
    if (dep) m.deprecated = dep;
    functionGroups[g].methods.push(m);
    continue;
  }

  const staticType = checker.getTypeOfSymbolAtLocation(sym, decl);
  const ctors = staticType.getConstructSignatures();
  const ownFile = fileTag(decl);
  const description = bestDoc(sym);

  if (ctors.length > 0) {
    const instanceType = ctors[0].getReturnType();
    const isBuiltin = !!staticType.getProperty('isInternalComponent');
    const inst = extractMembers(instanceType, false, ownFile);
    const stat = extractMembers(staticType, true, ownFile);
    const baseSym = instanceType.getBaseTypes?.()?.[0]?.getSymbol?.();
    const baseName = resolveBaseName(baseSym);
    const info: ClassInfo = {
      name, description,
      kind: isBuiltin ? 'component' : 'class',
      properties: inst.properties, methods: inst.methods,
    };
    if (stat.properties.length) info.staticProperties = stat.properties;
    if (stat.methods.length) info.staticMethods = stat.methods;
    if (baseName) info.baseClass = baseName;
    if (isBuiltin) {
      info.group = groupOf(decl);
      components[name] = info;
    } else {
      classes[name] = info;
    }
  } else if (sym.flags & (ts.SymbolFlags.Interface | ts.SymbolFlags.TypeAlias)) {
    types.push({ name, description });
  } else if (checker.getPropertiesOfType(staticType).length > 0) {
    // singleton / namespace object: Runtime, props, BVH, HitMesh, AssetManager, Skybox
    const mem = extractMembers(staticType, false, ownFile);
    if (mem.properties.length || mem.methods.length) {
      classes[name] = {
        name, description, kind: 'singleton',
        properties: mem.properties, methods: mem.methods,
      };
    }
  }

}

// ---------------------------------------------------------------------------
// Second pass: document the nested classes collected above (Keyboard, Mouse,
// TouchController, GamepadController). They are part of the surface an author
// touches even though the barrel does not export them directly.
// ---------------------------------------------------------------------------
for (const [name, t] of nestedCandidates) {
  if (classes[name] || components[name] || functionGroups[name]) continue;
  const sym = t.getSymbol()!;
  const d = declOf(sym)!;
  const mem = extractMembers(t, false, fileTag(d));
  if (!mem.properties.length && !mem.methods.length) continue;
  classes[name] = {
    name, description: bestDoc(sym), kind: 'class',
    properties: mem.properties, methods: mem.methods,
  };
}

// ---------------------------------------------------------------------------
// Decorators: methods on the NON-exported Props/Decorators classes
// ---------------------------------------------------------------------------
const decorators: { name: string; syntax: string; description: string }[] = [];
const propsExport = moduleExports.find(s => s.getName() === 'props');
if (propsExport) {
  const target = propsExport.flags & ts.SymbolFlags.Alias
    ? checker.getAliasedSymbol(propsExport) : propsExport;
  const propsDecl = declOf(target);
  if (propsDecl) {
    const propsType = checker.getTypeOfSymbolAtLocation(target, propsDecl);
    const collect = (type: ts.Type, prefix: string) => {
      for (const m of checker.getPropertiesOfType(type)) {
        if (skipMember(m)) continue;
        const d = declOf(m)!;
        const t = checker.getTypeOfSymbolAtLocation(m, d);
        const sigs = t.getCallSignatures();
        const full = prefix ? `${prefix}.${m.getName()}` : m.getName();
        if (sigs.length) {
          const params = cleanType(checker.signatureToString(sigs[0], d, TYPE_FLAGS))
            .replace(/\s*:\s*typeof decoratorFunc\s*$/, '')
            .replace(/\s*:\s*\([^)]*\)\s*=>\s*void\s*$/, '');
          decorators.push({ name: full, syntax: `@RE.props.${full}${params}`, description: bestDoc(m) });
        } else if (!prefix && (m.getName() === 'list' || m.getName() === 'map')) {
          collect(t, m.getName());
        }
      }
    };
    collect(propsType, '');
    decorators.sort((a, b) => a.name.localeCompare(b.name));
  }
}

// ---------------------------------------------------------------------------
// Emit / check
// ---------------------------------------------------------------------------
let engineProjectVersion: number | undefined;
try {
  engineProjectVersion = JSON.parse(
    fs.readFileSync(path.join(project, 'rogue-config.json'), 'utf8')).projectVersion;
} catch { /* optional */ }

const payload = {
  schemaVersion: SCHEMA_VERSION,
  generatedAt: new Date().toISOString(),
  engineProjectVersion,
  sourceProject: path.basename(project), // basename only: never leak local paths into a public repo
  counts: {
    classes: Object.keys(classes).length,
    components: Object.keys(components).length,
    functionGroups: Object.keys(functionGroups).length,
    decorators: decorators.length,
    types: types.length,
  },
  classes, components, functionGroups, decorators, types,
};

// Measure type-resolution health on the members we actually emit.
let anyCount = 0;
let typedCount = 0;
for (const bucket of [classes, components] as const) {
  for (const ci of Object.values(bucket)) {
    for (const p of [...ci.properties, ...(ci.staticProperties ?? [])]) {
      typedCount++;
      if (p.type === 'any' || p.type === 'error') anyCount++;
    }
  }
}
const degraded = typedCount ? anyCount / typedCount : 0;
if (degraded > 0.10) {
  console.warn(`WARN: ${(degraded * 100).toFixed(1)}% of emitted properties are "any" — ` +
    `"three" may have failed to resolve. JSDoc and member names are still correct.`);
} else {
  console.log(`Type resolution: ${(100 - degraded * 100).toFixed(1)}% of properties fully typed.`);
}

const outPath = path.join(REPO_ROOT, 'data', 'engine-api.json');
const prev = fs.existsSync(outPath)
  ? JSON.parse(fs.readFileSync(outPath, 'utf8')) as typeof payload
  : null;

if (prev) {
  const flat = (p: typeof payload) => {
    const out = new Set<string>();
    for (const bucket of ['classes', 'components', 'functionGroups'] as const) {
      for (const [cn, ci] of Object.entries(p[bucket] ?? {})) {
        out.add(cn);
        for (const k of ['properties', 'methods', 'staticProperties', 'staticMethods'] as const) {
          for (const m of (ci as ClassInfo)[k] ?? []) out.add(`${cn}.${m.name}`);
        }
      }
    }
    for (const d of p.decorators ?? []) out.add(`props.${d.name}`);
    return out;
  };
  const before = flat(prev);
  const after = flat(payload);
  const added = [...after].filter(x => !before.has(x));
  const removed = [...before].filter(x => !after.has(x));
  if (added.length) console.log(`\n+ Added (${added.length}):\n  ${added.slice(0, 40).join('\n  ')}`);
  if (removed.length) console.log(`\n- Removed (${removed.length}):\n  ${removed.slice(0, 40).join('\n  ')}`);
  if (!added.length && !removed.length) console.log('\nNo API changes vs the committed JSON.');
}

console.log(`\nclasses=${payload.counts.classes} components=${payload.counts.components} ` +
  `functionGroups=${payload.counts.functionGroups} decorators=${payload.counts.decorators} ` +
  `types=${payload.counts.types}`);

if (checkOnly) {
  console.log('\n--check: nothing written.');
  process.exit(0);
}

fs.mkdirSync(path.dirname(outPath), { recursive: true });
fs.writeFileSync(outPath, JSON.stringify(payload, null, 2) + '\n', 'utf8');
console.log(`\nWrote ${path.relative(REPO_ROOT, outPath)}`);
